# Generated by Django 6.1.1 on 2026-09-18 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('little_lemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='catagory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='catagory', to='little_lemon_app.catagory', unique=True),
        ),
    ]
